### ISSUE TITLE
Make system prompt customizable.

### ISSUE THREAD

**Issue by b-boehne** [dave1010/clipea#13]
I felt that clipea didn't respect my OS nearly enough (always recommended I use `apt` even though I am on Mac.  
So I think making the system prompt customizable for everyone would be beneficial.

I'll probably submit a PR myself soon.

**Comment by dave1010** [comment]
Thanks. Can you give any examples?

The OS gets provided as part of the environment that's sent to Clippy, so it should know what to use to install stuff. It might be that the prompt needs to be a bit more forceful there.

Having it fully customisable would be cool though. Maybe a `~/.clipea` file.

**Comment by b-boehne** [comment]
I've had varying responses for these kind of prompts. e.g.
```bash
?? deinstall clipea from my system
📎🟢 $ pip uninstall clipea
```
or `sudo apt-get remove clipea`

they went away after editing the last line of system-prompt to this:
`Important: Every command you output will automatically be executed in this env, be careful to only output commands which will work on this operating system and shell: `

But will still output `apt-get` stuff if my prompt is `deinstall clipea from my ubuntu system` which seems good.
