### ISSUE TITLE
No way to change the openai key?

### ISSUE THREAD

**Issue by mpr1255** [dave1010/clipea#15]
`clipea setup` makes no provision for a deprecated key. How can we set a new one??

**Comment by mpr1255** [comment]
I also couldn't find where the key is saved in config files. Confusing!

**Comment by edouard-sn** [comment]
You should be able to do so now. :)
https://github.com/dave1010/clipea/blob/1b7977efab68b32125ff51b3708a91bcbd4d1fc2/clipea/commands.py#L24

**Comment by dave1010** [comment]
Thanks @edouard-sn, much appreciated!
