### ISSUE TITLE
Rewrite in Python

### ISSUE THREAD

**Issue by dave1010** [dave1010/clipea#3]
(maybe)

Clipea depends on `llm` anyway, so Python is required.

May allow integrating with LangChain too.

Flask or FastAPI might be good for the CLI

**Comment by vividfog** [comment]
In some circles there's a bit of stigma against php, rational or not. So, passing a sniff test of a larger population, and the AI early adopter population in particular, I think "Made With Python™" is a selling point worth pursuing. Not to mention that forks and PRs are then probably going to be more viable for more folks, therefore more frequent too.

**Comment by dave1010** [comment]
Yup, agreed completely. Also LLMs seem to prefer Python and it's best to do what they say!

**Comment by garyo** [comment]
Get GPT to do the port! :-)

**Comment by Mcilie** [comment]
workin on it

**Comment by jaromrax** [comment]
Encouragments. With pypi, a straightforward install, low effort mod for masses. Thanks
